"""Public API for training baseline v2."""

from .constants import (
    ABLATION_FEATURE_SET_COLUMNS,
    BOOTSTRAP_ROUNDS,
    BOOTSTRAP_SEED,
    CFA_GATED_KEYS,
    CFA_VALIDITY_QUANTILE,
    CONTROL_MINIMAL_KEYS,
    DEGRADATION_EVAL_SPLITS,
    DEGRADATION_SPECS,
    ECE_BINS,
    FEATURE_SET_COLUMNS,
    MODEL_SPECS,
    TARGET_FPR,
)
from .degradation import (
    annotate_real_jpeg_subsampling,
    apply_degradation,
    build_nuisance_eval_frame,
    detect_jpeg_subsampling,
    extract_degraded_feature_frame,
)
from .metrics import auc_bootstrap_ci, expected_calibration_error, safe_logit, split_metrics, threshold_at_target_fpr
from .feature_audit import run_feature_shortcut_audit
from .phase_closure import run_training_phase_closure
from .pipeline import (
    add_conditional_cfa_gates,
    apply_conditional_cfa_threshold,
    build_cfa_gate_coverage,
    evaluate_selected_by_generator,
    evaluate_selected_candidate,
    load_training_table,
    run_training_baseline,
    run_training_with_feature_audit,
    save_model_parameters,
    split_frames,
    train_candidates,
    train_candidates_with_feature_sets,
)

__all__ = [
    "ABLATION_FEATURE_SET_COLUMNS",
    "BOOTSTRAP_ROUNDS",
    "BOOTSTRAP_SEED",
    "CFA_GATED_KEYS",
    "CFA_VALIDITY_QUANTILE",
    "CONTROL_MINIMAL_KEYS",
    "DEGRADATION_EVAL_SPLITS",
    "DEGRADATION_SPECS",
    "ECE_BINS",
    "FEATURE_SET_COLUMNS",
    "MODEL_SPECS",
    "TARGET_FPR",
    "add_conditional_cfa_gates",
    "annotate_real_jpeg_subsampling",
    "apply_conditional_cfa_threshold",
    "apply_degradation",
    "auc_bootstrap_ci",
    "build_nuisance_eval_frame",
    "build_cfa_gate_coverage",
    "detect_jpeg_subsampling",
    "evaluate_selected_by_generator",
    "evaluate_selected_candidate",
    "expected_calibration_error",
    "extract_degraded_feature_frame",
    "load_training_table",
    "run_training_baseline",
    "run_feature_shortcut_audit",
    "run_training_phase_closure",
    "run_training_with_feature_audit",
    "safe_logit",
    "save_model_parameters",
    "split_frames",
    "split_metrics",
    "threshold_at_target_fpr",
    "train_candidates",
    "train_candidates_with_feature_sets",
]
